name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements_clean.txt ]; then pip install -r requirements_clean.txt; fi
          # Linters (optional)
          pip install black==24.8.0 isort==5.13.2 flake8==7.1.1

      - name: Lint
        run: |
          black --check .
          isort --check-only .
          flake8 .

      - name: Integration test (starts server internally)
        run: |
          python test_endpoints.py
