name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements_clean.txt ]; then pip install -r requirements_clean.txt; fi
          pip install black==24.8.0 isort==5.13.2 flake8==7.1.1 requests

      - name: Auto-format code
        run: |
          black .
          isort .

      - name: Lint
        run: |
          flake8 .

      - name: Run integration test
        run: |
          python test_endpoints.py
