
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_clean.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --max-line-length=88 --extend-ignore=E203

    - name: Run FastAPI tests
      run: |
        python -m uvicorn main:app --host 127.0.0.1 --port 8000 &
        sleep 5
        python test_endpoints.py
